### ISSUE TITLE
Indicate universal currency

### ISSUE THREAD

**Issue by queer** [queer/amyism.pro#7]
The universal currency used to be banana, but is now cake. We need to indicate this.

**Comment by spotlightishere** [comment]
Perhaps this would be best remedied by replacing `banana` with `cake`, and find an acceptable image?
Unfortunately, I'm not certain of to what the universe expects for cake in order to make any suggestions - open to submissions.

**Comment by Ratismal** [comment]
Could we potentially make the cakes using bananas, to ease the transition period?

**Comment by queer** [comment]
Unfortunately, bananacakes were banned 14 years ago after the war, so we can't do that @Ratismal :(

**Comment by Ratismal** [comment]
![image](https://user-images.githubusercontent.com/1059362/86184846-327b1300-baf2-11ea-9f67-eac2956054bf.png)
